## reference: https://docs.travis-ci.com/user/languages/r/

language: r
r: bioc-release

cache: packages

r_github_packages:
  - r-lib/covr
  - pkimes/upbmData
  - pkimes/upbmAux

after_success:
  - Rscript -e 'library(covr); codecov()'
