#' Combinatorial Files to PBMExerpiment Object
#'
#' Helper function to read in a set of combinatorial files generated by 
#' the Universal PBM Analysis Suite into a format similar to raw PBM
#' data read using \code{buildPBMExerpiment}.
#'
#' @param tab data.frame with at least a single `combn` column
#'        corresponding to PBM "combinatorial.txt" file paths. 
#'
#' @return
#' SummarizedExperiment object containing PBM data.
#'
#' @details
#' If a `name` column is included int he input table, these are used as the
#' corresponding IDs for each sample/row. If IDs are not provided, the
#' file names are used. Sample IDs must be unique, and an error is thrown
#' if any samples have a common ID.
#' All other columns (aside from `combn` and `name`) in `tab` will be added to
#' the `colData` of the returned SummarizedExperiment object. Any sample
#' information, e.g. replicate or condition information can be included in
#' `tab`.
#' 
#' @md
#' @import SummarizedExperiment
#' @importFrom dplyr rename select
#' @importFrom readr read_tsv
#' @importFrom purrr reduce
#' @export
#' @author Patrick Kimes
comb2PBMExperiment <- function(tab) {
    stopifnot(is(tab, "data.frame"))
    stopifnot("combn" %in% names(tab))
    
    ## make sure all files exist
    if (!all(file.exists(tab$combn))) {
        stop("Not all combinatorial files in table exist.")
    }

    ## make sure all files are combinatorial files
    if (!all(grepl("_combinatorial\\.txt$", tab$combn))) {
        stop("All files must be combinatorial files with standard suffix, '_combinatorial.txt'.")
    }
    
    ## check sample IDs
    if (! "name" %in% names(tab)) {
        cat("Since 'name' column not present in table, using file basenames as sample IDs.\n")
        tab$name <- gsub("_combinatorial\\.txt$", "", basename(tab$combn))
    }
    if (any(duplicated(tab$name))) {
        stop("Sample names/IDs must be unique.")
    }
    
    ## read in files
    gpr <- lapply(tab$combn, readr::read_tsv, col_names = c("intensity", "Sequence"),
                  col_types = "dc", progress = FALSE)

    ## check that dimensions are the same
    nprobes <- unlist(lapply(gpr, nrow))
    if (min(nprobes) / max(nprobes) < 0.95) {
        stop("Not all samples have (roughly) same number of probes.\n",
             "Please only supply samples from a single design.\n",
             paste0(paste0(tab$name, ":", nprobes), collapse = "; "))
    }

    ## merge samples
    gpr <- mapply(function(g, n) { dplyr::rename(g, !!n := intensity) }, gpr, tab$name, SIMPLIFY = FALSE)
    assay_table <- purrr::reduce(gpr, left_join, by = c("Sequence"))

    ## check that probe sequences match across samples
    if (nrow(assay_table) != max(nprobes)) {
        stop("Not all samples have same probe sequences.\n",
             "Please only supply samples from a single design.")
    }
    
    ## create row data, just probe sequence
    rowdat <- as.data.frame(dplyr::select(assay_table, Sequence), optional = TRUE)
    
    ## create column data, just probe sequence
    coldat <- cbind(data.frame(scan = rep("Combinatorial", nrow(tab)),
                               stringsAsFactors = FALSE),
                    dplyr::select(tab, -combn, -name))

    ## create assay list
    assaydat <- list(fore = as.matrix(dplyr::select(assay_table, -Sequence)))

    ## SummarizedExperiment
    SummarizedExperiment(assays = assaydat, rowData = rowdat, colData = coldat,
                         metadata = list(steps = list(),
                                         spatialAdjustment = NULL,
                                         backgroundCorrection = NULL,
                                         betweenArrayNormalization = NULL))
}
